{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(process_resident_memory_bytes, pod)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  }
 ]
}
{
 "title": "gRPC",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "timewindow", "label": "Time Window", "query": "5m,10m,15m,30m,1h,4h" }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_server_method)(rate(grpc_io_server_completed_rpcs[$timewindow]))",
     "legendFormat": "{{grpc_server_method}}"
    }
   ]
  },
  {
   "title": "95%-ile Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket[$timewindow])) by (grpc_server_method, le))",
     "legendFormat": "{{grpc_server_method}}"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_client_method)(rate(grpc_io_client_completed_rpcs[$timewindow]))",
     "legendFormat": "{{grpc_client_method}}"
    }
   ]
  },
  {
   "title": "95%-ile Client Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket[$timewindow])) by (grpc_client_method, le))",
     "legendFormat": "{{grpc_client_method}}"
    }
   ]
  }
 ]
}
{
 "title": "Redis Connection Latency",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(redis_connectlatency_bucket[5m])) by (component, le))",
     "legendFormat": "{{component}} 10 percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(redis_connectlatency_bucket[5m])) by (component, le))",
     "legendFormat": "{{component}} 50 percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(redis_connectlatency_bucket[5m])) by (component, le))",
     "legendFormat": "{{component}} 75 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(redis_connectlatency_bucket[5m])) by (component, le))",
     "legendFormat": "{{component}} 95 percentile"
    }
   ]
  }
 ]
}
{
 "title": "Storage asd",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "timewindow", "label": "Time Window", "query": "5m,10m,15m,30m,1h,4h" }
  ]
 },
 "panels": [
  {
   "title": "Write Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(statestore_createticketcount[$timewindow]))",
     "legendFormat": "Create Ticket"
    },
    {
     "expr": "sum(rate(statestore_deleteticketcount[$timewindow]))",
     "legendFormat": "Delete Ticket Count"
    },
    {
     "expr": "sum(rate(statestore_indexticketcount[$timewindow]))",
     "legendFormat": "Index Ticket Count"
    },
    {
     "expr": "sum(rate(statestore_deindexticketcount[$timewindow]))",
     "legendFormat": "Deindex Ticket Count"
    },
    {
     "expr": "sum(rate(statestore_addticketstoignorelistcount[$timewindow]))",
     "legendFormat": "IgnoreList Add Count"
    },
    {
     "expr": "sum(rate(statestore_deleteticketfromignorelistcount[$timewindow]))",
     "legendFormat": "IgnoreList Delete Count"
    },
    {
     "expr": "sum(rate(statestore_updateassignmentcount[$timewindow]))",
     "legendFormat": "Update Assignment Count"
    }
   ]
  },
  {
   "title": "Read Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(statestore_getassignmentscount[$timewindow]))",
     "legendFormat": "Get Assignment Count"
    },
    {
     "expr": "sum(rate(statestore_filterticketcount[$timewindow]))",
     "legendFormat": "Filter Ticket Count"
    },
    {
     "expr": "sum(rate(statestore_getticketcount[$timewindow]))",
     "legendFormat": "Get Ticket Count"
    }
   ]
  },
  {
   "title": "Time Elapsed: CreateTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_createtickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: DeleteTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_deletetickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: GetTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_gettickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: GetAssignments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_getassignmentstime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: IndexTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_indextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: DeindexTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_deindextickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: FilterTicket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_filtertickettime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: UpdateAssignment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_updateassignmenttime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: AddTicketsToIgnoreList",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_addticketstoignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  },
  {
   "title": "Time Elapsed: DeleteTicketFromIgnoreList",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "10 Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "25 Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "50 Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "75 Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(statestore_deleteticketfromignorelisttime_bucket[$timewindow])) by (le))",
     "legendFormat": "95 Percentile"
    }
   ]
  }
 ]
}
{
 "title": "Tickets",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "timewindow", "label": "Time Window", "query": "5m,10m,15m,30m,1h,4h" }
  ]
 },
 "panels": [
  {
   "title": "Ticket Flow",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(frontend_tickets_created[$timewindow]))",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(rate(frontend_tickets_deleted[$timewindow]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Assignments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(frontend_tickets_assignments_retrieved[$timewindow]))",
     "legendFormat": "Assignments Retrieved"
    }
   ]
  }
 ]
}