apiVersion: v1
kind: Pod
metadata:
  name: om-facade
  namespace: open-match-facade
spec:
  containers:
    - name: om-facade
      image: mikebiondi/open-match-facade
      ports:
        - containerPort: 8990
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: om-facade-service
  namespace: open-match-facade
spec:
  selector:
    app: om-facade
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8990

#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: om-facade-service
#  namespace: open-match-facade
#subsets:
#  - addresses:
#      - ip: 207.246.124.28
#    ports:
#      - port: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: om-facade-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: om-facade-service
              servicePort: 8080
