---
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: om-facade
#  namespace: open-match-facade
#spec:
#  containers:
#    - name: om-facade
#      image: mikebiondi/open-match-facade
#      ports:
#        - containerPort: 8990
#          protocol: TCP

apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-facade
  namespace: open-match-facade
  labels:
    app: om-facade
spec:
  selector:
    matchLabels:
      app: om-facade
  replicas: 2
  template:
    metadata:
      name: om-facade
      labels:
        app: om-facade
    spec:
      containers:
        - name: om-facade
          image: mikebiondi/open-match-facade
          ports:
            - containerPort: 8990
---
apiVersion: v1
kind: Service
metadata:
  name: om-facade-service
  namespace: open-match-facade
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8990
      nodePort: 32424
      targetPort: 8990
  selector:
    app: om-facade
  externalIPs:
    - "207.246.124.28"
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: om-facade-service
#  namespace: open-match-facade
#subsets:
#  - addresses:
#      - ip: 207.246.124.28
#    ports:
#      - port: 8080

#---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: om-facade-service-ingress
#  namespace: open-match-facade
#spec:
#  backend:
#    serviceName: om-facade-service
#    servicePort: 8990
