apiVersion: v1
kind: Pod
metadata:
  name: om-facade
  namespace: open-match-facade
spec:
  containers:
    - name: open-match-facade
      image: mikebiondi/open-match-facade
      resources:
        limits:
          memory: "256Mi"
        requests:
          memory: "256Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "256M", "--vm-hang", "1"]
