apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-mounted-kube-persistent-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-persistent-storage
spec:
  storageClassName: nfs-mounted-kube-persistent-storage
  #storageClassName: local-storage
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/kube-persistent-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-00
